name: 02 - Workflow Events
on: 
  push:
  pull_request:
  schedule:
    - cron: "*/5 * * * *" # Trigger action every 5 minutes
  workflow_dispatch: # Allow to trigger action from github ui

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: "echo Event name: ${{ github.event_name }}"
  
  